# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GOKFellipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GOKFellipe

  pod 'SnapKit'
  
  target 'GOKFellipeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'GOKFellipeUITests' do
    # Pods for testing
  end

end
